### ISSUE TITLE
Getting lots of 00000002 (null) when I try to use n64sym

### ISSUE THREAD

**Issue by ethteck** [shygoo/n64sym#4]
I'm trying to use n64sym from WSL 2 (Ubuntu). I cloned the repo, ran `make`, and when I do `./bin/n64sym ../../path/to/papermario.z64 -s`, the output looks like a lot of
```
00000002 (null)
00000002 (null)
00000002 (null)
00000002 (null)
00000002 (null)
00000002 (null)
00000006 (null)
00000006 (null)
00000002 (null)
```
I tried the windows .exe as well, but I'm missing a bunch of dlls apparently. The online version of the tool works with the same input file, so I know that's good.

**Comment by shygoo** [comment]
I was able to reproduce this in WSL. I'll try to fix it when I get a chance. FWIW the dll issue with the windows build should be fixed now.

**Comment by ethteck** [comment]
Awesome, thanks!
